name: Hexo Blog CI/CD
on:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_ENV: production
      TZ: Asia/Shanghai

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: npm
          check-latest: true

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}-${{ hashFiles('package.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm ci --prefer-offline --no-audit --no-fund

      - name: Clean Before Generate
        run: npx hexo clean

      - name: Generate Static Files
        run: |
          npx hexo generate --bail
          echo "Public directory size:"
          du -sh public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          force_orphan: true
          allow_empty_commit: false
          keep_files: |
            CNAME
            .nojekyll

      - name: Verify Deployment
        run: |
          echo "Deployment completed successfully!"
